#pragma once

// ARK (291.0) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARK_DinoBlueprintBase_RootBoneName_Mounted_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Mounted_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3078
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3078_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4007
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4007_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_624
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_624_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3077
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3077_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3076
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3076_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3075
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3075_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3074
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3074_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4006
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4006_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4005
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4005_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3073
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3073_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3072
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3072_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4002
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4002_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_RotationOffsetBlendSpace_180
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_RotationOffsetBlendSpace_180_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4001
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4001_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3071
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3071_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3070
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3070_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4000
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_4000_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_3999
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_3999_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3069
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3069_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3068
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3068_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3067
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3067_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_623
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ModifyBone_623_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3066
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3066_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3065
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3065_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3064
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3064_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_174
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_174_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_173
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_GroundBones_173_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ApplyAdditive_228
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_ApplyAdditive_228_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3063
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3063_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3062
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_BlendListByBool_3062_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_3994
struct UDinoBlueprintBase_RootBoneName_Mounted_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_AnimGraphNode_SequencePlayer_3994_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Mounted_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Mounted.DinoBlueprintBase_RootBoneName_Mounted_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted
struct UDinoBlueprintBase_RootBoneName_Mounted_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Mounted_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
