#pragma once

// ARK (291.0) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARK_DinoBlueprintBase_RootTransformIK_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootTransformIK_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3762
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3762_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ModifyBone_738
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ModifyBone_738_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3761
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3761_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_RotationOffsetBlendSpace_246
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_RotationOffsetBlendSpace_246_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3760
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3760_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3759
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3759_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4618
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4618_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3758
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3758_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3757
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3757_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4617
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4617_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4616
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4616_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3756
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3756_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4615
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4615_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3755
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3755_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3754
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3754_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4613
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4613_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3753
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3753_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3752
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3752_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4612
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4612_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4611
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4611_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3751
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3751_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3750
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3750_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4610
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4610_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4609
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4609_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4608
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_SequencePlayer_4608_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendSpacePlayer_192
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendSpacePlayer_192_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3748
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3748_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3747
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_BlendListByBool_3747_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ApplyAdditive_294
struct UDinoBlueprintBase_RootTransformIK_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_AnimGraphNode_ApplyAdditive_294_Params
{
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootTransformIK_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootTransformIK.DinoBlueprintBase_RootTransformIK_C.ExecuteUbergraph_DinoBlueprintBase_RootTransformIK
struct UDinoBlueprintBase_RootTransformIK_C_ExecuteUbergraph_DinoBlueprintBase_RootTransformIK_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
