#pragma once

// ARK (291.0) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARK_DinoBlueprintBase_RootBoneName_Ramming_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.BlueprintPlayAnimationEvent
struct UDinoBlueprintBase_RootBoneName_Ramming_C_BlueprintPlayAnimationEvent_Params
{
	class UAnimMontage**                               AnimationMontage;                                         // (Parm, ZeroConstructor, IsPlainOldData)
	float*                                             PlayRate;                                                 // (Parm, ZeroConstructor, IsPlainOldData)
	float                                              playedAnimLength;                                         // (Parm, OutParm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3648
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3648_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4511
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4511_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_714
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_714_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3647
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3647_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3646
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3646_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3645
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3645_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3644
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3644_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4510
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4510_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4509
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4509_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3643
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3643_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3642
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3642_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4506
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4506_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_RotationOffsetBlendSpace_222
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_RotationOffsetBlendSpace_222_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4505
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4505_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3641
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3641_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3640
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3640_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4504
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4504_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4503
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4503_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3639
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3639_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3638
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3638_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3637
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3637_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_713
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ModifyBone_713_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3636
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3636_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3635
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3635_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3634
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3634_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_228
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_228_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_227
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_GroundBones_227_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ApplyAdditive_282
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_ApplyAdditive_282_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3633
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3633_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3632
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3632_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4498
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4498_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3631
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3631_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3630
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3630_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3629
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_BlendListByBool_3629_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4497
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4497_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4496
struct UDinoBlueprintBase_RootBoneName_Ramming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_AnimGraphNode_SequencePlayer_4496_Params
{
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.BlueprintUpdateAnimation
struct UDinoBlueprintBase_RootBoneName_Ramming_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function DinoBlueprintBase_RootBoneName_Ramming.DinoBlueprintBase_RootBoneName_Ramming_C.ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming
struct UDinoBlueprintBase_RootBoneName_Ramming_C_ExecuteUbergraph_DinoBlueprintBase_RootBoneName_Ramming_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
