#pragma once

// ARK (291.0) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "ARK_GiantTurtle_AnimBlueprintNew_classes.hpp"

namespace sdk
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4432
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4432_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4431
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4431_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4430
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4430_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5159
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5159_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5158
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5158_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4429
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4429_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4428
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4428_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5157
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5157_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5156
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5156_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4427
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4427_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4426
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4426_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5155
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5155_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5154
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5154_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4425
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4425_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4424
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4424_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4423
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4423_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_773
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_773_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4422
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4422_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4421
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4421_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4420
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4420_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_270
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_270_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_269
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_GroundBones_269_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ApplyAdditive_360
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ApplyAdditive_360_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4419
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4419_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5149
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5149_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4433
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4433_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4416
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4416_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4415
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4415_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_774
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_ModifyBone_774_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendSpacePlayer_288
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendSpacePlayer_288_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4434
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4434_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4410
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4410_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5139
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_SequencePlayer_5139_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4409
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4409_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_RotationOffsetBlendSpace_270
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_RotationOffsetBlendSpace_270_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4407
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4407_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4406
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4406_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4405
struct UGiantTurtle_AnimBlueprintNew_C_EvaluateGraphExposedInputs_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_AnimGraphNode_BlendListByBool_4405_Params
{
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.BlueprintUpdateAnimation
struct UGiantTurtle_AnimBlueprintNew_C_BlueprintUpdateAnimation_Params
{
	float*                                             DeltaTimeX;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function GiantTurtle_AnimBlueprintNew.GiantTurtle_AnimBlueprintNew_C.ExecuteUbergraph_GiantTurtle_AnimBlueprintNew
struct UGiantTurtle_AnimBlueprintNew_C_ExecuteUbergraph_GiantTurtle_AnimBlueprintNew_Params
{
	int                                                EntryPoint;                                               // (Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
